/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lenguaje;

/**
 *
 * @author Melvin
 */
public class ecualizador extends javax.swing.JFrame {

    /**
     * Creates new form ecualizador
     */
    public ecualizador() {
        initComponents();
        inicio();
    }

    //En el constructor se inicializan los JScrollBar y jRadionButton
    public void inicio() {
        desFrecuencia1.setValue(5);
        desFrecuencia2.setValue(5);
        desFrecuencia3.setValue(5);
        desFrecuencia4.setValue(5);
        desFrecuencia5.setValue(5);
        optPlano.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoEcualizacion = new javax.swing.ButtonGroup();
        etiFrecuencia1 = new javax.swing.JLabel();
        desFrecuencia1 = new javax.swing.JScrollBar();
        chkFrecuencia1 = new javax.swing.JCheckBox();
        etiFrecuencia2 = new javax.swing.JLabel();
        desFrecuencia2 = new javax.swing.JScrollBar();
        chkFrecuencia2 = new javax.swing.JCheckBox();
        etiFrecuencia3 = new javax.swing.JLabel();
        desFrecuencia3 = new javax.swing.JScrollBar();
        chkFrecuencia3 = new javax.swing.JCheckBox();
        etiFrecuencia4 = new javax.swing.JLabel();
        desFrecuencia4 = new javax.swing.JScrollBar();
        chkFrecuencia4 = new javax.swing.JCheckBox();
        etiFrecuencia5 = new javax.swing.JLabel();
        desFrecuencia5 = new javax.swing.JScrollBar();
        chkFrecuencia5 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        optPelicula = new javax.swing.JRadioButton();
        optConcierto = new javax.swing.JRadioButton();
        optPlano = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        etiFrecuencia1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        desFrecuencia1.setBlockIncrement(2);
        desFrecuencia1.setMaximum(11);
        desFrecuencia1.setVisibleAmount(1);
        desFrecuencia1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        desFrecuencia1.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                desFrecuencia1AdjustmentValueChanged(evt);
            }
        });

        chkFrecuencia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkFrecuencia1ActionPerformed(evt);
            }
        });

        etiFrecuencia2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        desFrecuencia2.setBlockIncrement(2);
        desFrecuencia2.setMaximum(11);
        desFrecuencia2.setVisibleAmount(1);
        desFrecuencia2.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                desFrecuencia2AdjustmentValueChanged(evt);
            }
        });

        chkFrecuencia2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkFrecuencia2ActionPerformed(evt);
            }
        });

        etiFrecuencia3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        desFrecuencia3.setBlockIncrement(2);
        desFrecuencia3.setMaximum(11);
        desFrecuencia3.setVisibleAmount(1);
        desFrecuencia3.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                desFrecuencia3AdjustmentValueChanged(evt);
            }
        });

        chkFrecuencia3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkFrecuencia3ActionPerformed(evt);
            }
        });

        etiFrecuencia4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        desFrecuencia4.setBlockIncrement(15);
        desFrecuencia4.setMaximum(11);
        desFrecuencia4.setVisibleAmount(1);
        desFrecuencia4.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                desFrecuencia4AdjustmentValueChanged(evt);
            }
        });

        chkFrecuencia4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkFrecuencia4ActionPerformed(evt);
            }
        });

        etiFrecuencia5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        desFrecuencia5.setBlockIncrement(2);
        desFrecuencia5.setMaximum(11);
        desFrecuencia5.setVisibleAmount(1);
        desFrecuencia5.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                desFrecuencia5AdjustmentValueChanged(evt);
            }
        });

        chkFrecuencia5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkFrecuencia5ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ecualizaciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 153))); // NOI18N

        grupoEcualizacion.add(optPelicula);
        optPelicula.setText("Película");
        optPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optPeliculaActionPerformed(evt);
            }
        });

        grupoEcualizacion.add(optConcierto);
        optConcierto.setText("Concierto");
        optConcierto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optConciertoActionPerformed(evt);
            }
        });

        grupoEcualizacion.add(optPlano);
        optPlano.setText("Plano");
        optPlano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optPlanoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(optPelicula)
                    .addComponent(optConcierto)
                    .addComponent(optPlano))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(optPelicula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(optConcierto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(optPlano)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiFrecuencia1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkFrecuencia1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(desFrecuencia1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiFrecuencia2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(desFrecuencia2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiFrecuencia3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(desFrecuencia3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(chkFrecuencia2, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(chkFrecuencia3)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiFrecuencia4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkFrecuencia4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(desFrecuencia4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiFrecuencia5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkFrecuencia5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(desFrecuencia5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(44, 44, 44)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(etiFrecuencia1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(desFrecuencia1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(etiFrecuencia2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(desFrecuencia2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(etiFrecuencia3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(desFrecuencia3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(etiFrecuencia4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(desFrecuencia4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(etiFrecuencia5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(desFrecuencia5, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkFrecuencia5)
                            .addComponent(chkFrecuencia4)
                            .addComponent(chkFrecuencia3)
                            .addComponent(chkFrecuencia2)
                            .addComponent(chkFrecuencia1))))
                .addGap(18, 26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //evento que nos genera los valores y envia a la etiqueta correspondiente.
    private void desFrecuencia1AdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_desFrecuencia1AdjustmentValueChanged
        etiFrecuencia1.setText("" + desFrecuencia1.getValue());
    }//GEN-LAST:event_desFrecuencia1AdjustmentValueChanged
    //evento que nos genera los valores y envia a la etiqueta correspondiente.
    private void desFrecuencia2AdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_desFrecuencia2AdjustmentValueChanged
        etiFrecuencia2.setText("" + desFrecuencia2.getValue());
    }//GEN-LAST:event_desFrecuencia2AdjustmentValueChanged
    //evento que nos genera los valores y envia a la etiqueta correspondiente.
    private void desFrecuencia3AdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_desFrecuencia3AdjustmentValueChanged
        etiFrecuencia3.setText("" + desFrecuencia3.getValue());
    }//GEN-LAST:event_desFrecuencia3AdjustmentValueChanged
    //Asigna un valor pres-establecido por la opcion del RadioButton
    private void optPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optPeliculaActionPerformed
        desFrecuencia1.setValue(2);
        desFrecuencia2.setValue(5);
        desFrecuencia3.setValue(8);
        desFrecuencia4.setValue(5);
        desFrecuencia5.setValue(2);
    }//GEN-LAST:event_optPeliculaActionPerformed
    //Evento para activar o desactivar los ScrollBar con un CheckBox
    private void chkFrecuencia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkFrecuencia1ActionPerformed
        if (chkFrecuencia1.isSelected()) {
            desFrecuencia1.setEnabled(false);
        } else {
            desFrecuencia1.setEnabled(true);
        }

    }//GEN-LAST:event_chkFrecuencia1ActionPerformed
    //Evento para activar o desactivar los ScrollBar con un CheckBox
    private void chkFrecuencia2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkFrecuencia2ActionPerformed
        if (chkFrecuencia2.isSelected()) {
            desFrecuencia2.setEnabled(false);
        } else {
            desFrecuencia2.setEnabled(true);
        }
    }//GEN-LAST:event_chkFrecuencia2ActionPerformed
//Asigna un valor pres-establecido por la opcion del RadioButton
    private void optConciertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optConciertoActionPerformed
        desFrecuencia1.setValue(9);
        desFrecuencia2.setValue(5);
        desFrecuencia3.setValue(1);
        desFrecuencia4.setValue(5);
        desFrecuencia5.setValue(9);
    }//GEN-LAST:event_optConciertoActionPerformed
//Asigna un valor pres-establecido por la opcion del RadioButton
    private void optPlanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optPlanoActionPerformed
        desFrecuencia1.setValue(5);
        desFrecuencia2.setValue(5);
        desFrecuencia3.setValue(5);
        desFrecuencia4.setValue(5);
        desFrecuencia5.setValue(5);
    }//GEN-LAST:event_optPlanoActionPerformed
    //Evento para activar o desactivar los ScrollBar con un CheckBox
    private void chkFrecuencia3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkFrecuencia3ActionPerformed
        if (chkFrecuencia3.isSelected()) {
            desFrecuencia3.setEnabled(false);
        } else {
            desFrecuencia3.setEnabled(true);
        }
    }//GEN-LAST:event_chkFrecuencia3ActionPerformed
    //Evento para activar o desactivar los ScrollBar con un CheckBox
    private void chkFrecuencia4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkFrecuencia4ActionPerformed
        if (chkFrecuencia4.isSelected()) {
            desFrecuencia4.setEnabled(false);
        } else {
            desFrecuencia4.setEnabled(true);
        }
    }//GEN-LAST:event_chkFrecuencia4ActionPerformed
    //Evento para activar o desactivar los ScrollBar con un CheckBox
    private void chkFrecuencia5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkFrecuencia5ActionPerformed
        if (chkFrecuencia5.isSelected()) {
            desFrecuencia5.setEnabled(false);
        } else {
            desFrecuencia5.setEnabled(true);
        }
    }//GEN-LAST:event_chkFrecuencia5ActionPerformed
    //evento que nos genera los valores y envia a la etiqueta correspondiente.
    private void desFrecuencia4AdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_desFrecuencia4AdjustmentValueChanged
        etiFrecuencia4.setText("" + desFrecuencia4.getValue());
    }//GEN-LAST:event_desFrecuencia4AdjustmentValueChanged
    //evento que nos genera los valores y envia a la etiqueta correspondiente.
    private void desFrecuencia5AdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_desFrecuencia5AdjustmentValueChanged
        etiFrecuencia5.setText("" + desFrecuencia5.getValue());

    }//GEN-LAST:event_desFrecuencia5AdjustmentValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ecualizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ecualizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ecualizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ecualizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ecualizador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkFrecuencia1;
    private javax.swing.JCheckBox chkFrecuencia2;
    private javax.swing.JCheckBox chkFrecuencia3;
    private javax.swing.JCheckBox chkFrecuencia4;
    private javax.swing.JCheckBox chkFrecuencia5;
    private javax.swing.JScrollBar desFrecuencia1;
    private javax.swing.JScrollBar desFrecuencia2;
    private javax.swing.JScrollBar desFrecuencia3;
    private javax.swing.JScrollBar desFrecuencia4;
    private javax.swing.JScrollBar desFrecuencia5;
    private javax.swing.JLabel etiFrecuencia1;
    private javax.swing.JLabel etiFrecuencia2;
    private javax.swing.JLabel etiFrecuencia3;
    private javax.swing.JLabel etiFrecuencia4;
    private javax.swing.JLabel etiFrecuencia5;
    private javax.swing.ButtonGroup grupoEcualizacion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton optConcierto;
    private javax.swing.JRadioButton optPelicula;
    private javax.swing.JRadioButton optPlano;
    // End of variables declaration//GEN-END:variables
}
