/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lenguaje;

import javax.swing.JOptionPane;

/**
 *
 * @author Melvin
 */
public class oficinas extends javax.swing.JFrame {

    //Variables globales para el conteo de las luces.
    int priencendidas = 3;
    int priapagadas = 3;
    int secunencendidas = 3;
    int secunapaga = 0;
    int seguencendido = 0;
    int seguapagado = 0;

    /**
     * Creates new form oficinas
     */
    public oficinas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        chckPrincipal1 = new javax.swing.JCheckBox();
        chckSecundaria1 = new javax.swing.JCheckBox();
        chckSeguridad1 = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        chckPrincipal2 = new javax.swing.JCheckBox();
        chckSecundaria2 = new javax.swing.JCheckBox();
        chckSeguridad2 = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        chckPrincipal3 = new javax.swing.JCheckBox();
        chckSecundaria3 = new javax.swing.JCheckBox();
        chckSeguridad3 = new javax.swing.JCheckBox();
        jToolBar1 = new javax.swing.JToolBar();
        btnApagar = new javax.swing.JButton();
        btnEncender = new javax.swing.JButton();
        btnDia = new javax.swing.JButton();
        btnNoche = new javax.swing.JButton();
        btnPrincipal = new javax.swing.JButton();
        btnSecundarias = new javax.swing.JButton();
        btnSeguridad = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuActivacion = new javax.swing.JMenu();
        menuApagarTodas = new javax.swing.JMenuItem();
        menuEncenderTodas = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuDia = new javax.swing.JMenu();
        menuOficina1 = new javax.swing.JMenuItem();
        menuOficina2 = new javax.swing.JMenuItem();
        menuOficina3 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        menuTodas = new javax.swing.JMenuItem();
        menuNoche = new javax.swing.JMenu();
        menuOficina1Noche = new javax.swing.JMenuItem();
        menuOficina2Noche = new javax.swing.JMenuItem();
        menuOficina3Noche = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        menuTodasNoches = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuSalir = new javax.swing.JMenuItem();
        menuInfo = new javax.swing.JMenu();
        menuPrincipales = new javax.swing.JMenuItem();
        menuSecundarias = new javax.swing.JMenuItem();
        menuSeguridad = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        menuAcercade = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Oficina 1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 102))); // NOI18N

        chckPrincipal1.setText("Luz Principal");

        chckSecundaria1.setText("Luz Secundaria");

        chckSeguridad1.setText("Luz de Seguridad");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chckPrincipal1)
                    .addComponent(chckSecundaria1)
                    .addComponent(chckSeguridad1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chckPrincipal1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chckSecundaria1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chckSeguridad1)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Oficina 2", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 102))); // NOI18N

        chckPrincipal2.setText("Luz Principal");

        chckSecundaria2.setText("Luz Secundaria");

        chckSeguridad2.setText("Luz de Seguridad");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chckPrincipal2)
                    .addComponent(chckSecundaria2)
                    .addComponent(chckSeguridad2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chckPrincipal2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chckSecundaria2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chckSeguridad2)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Oficina 3", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 153))); // NOI18N

        chckPrincipal3.setText("Luz Principal");

        chckSecundaria3.setText("Luz Secundaria");

        chckSeguridad3.setText("Luz de Seguridad");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chckPrincipal3)
                    .addComponent(chckSecundaria3)
                    .addComponent(chckSeguridad3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chckPrincipal3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chckSecundaria3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chckSeguridad3)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jToolBar1.setRollover(true);

        btnApagar.setText("Apagar Todas");
        btnApagar.setFocusable(false);
        btnApagar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnApagar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnApagar);

        btnEncender.setText("Encender Todas");
        btnEncender.setFocusable(false);
        btnEncender.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEncender.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEncender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncenderActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEncender);

        btnDia.setText("Dia");
        btnDia.setFocusable(false);
        btnDia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDia);

        btnNoche.setText("Noche");
        btnNoche.setFocusable(false);
        btnNoche.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNoche.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNocheActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNoche);

        btnPrincipal.setText("Principales");
        btnPrincipal.setFocusable(false);
        btnPrincipal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPrincipal.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrincipalActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPrincipal);

        btnSecundarias.setText("Secundarias");
        btnSecundarias.setFocusable(false);
        btnSecundarias.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSecundarias.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSecundarias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSecundariasActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSecundarias);

        btnSeguridad.setText("Seguridad");
        btnSeguridad.setFocusable(false);
        btnSeguridad.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSeguridad.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSeguridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeguridadActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSeguridad);

        menuActivacion.setText("Activación");

        menuApagarTodas.setText("Apagar Todas");
        menuApagarTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuApagarTodasActionPerformed(evt);
            }
        });
        menuActivacion.add(menuApagarTodas);

        menuEncenderTodas.setText("Encender Todas");
        menuEncenderTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEncenderTodasActionPerformed(evt);
            }
        });
        menuActivacion.add(menuEncenderTodas);
        menuActivacion.add(jSeparator1);

        menuDia.setText("Dia");

        menuOficina1.setText("Oficina 1");
        menuOficina1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOficina1ActionPerformed(evt);
            }
        });
        menuDia.add(menuOficina1);

        menuOficina2.setText("Oficina 2");
        menuOficina2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOficina2ActionPerformed(evt);
            }
        });
        menuDia.add(menuOficina2);

        menuOficina3.setText("Oficina 3");
        menuOficina3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOficina3ActionPerformed(evt);
            }
        });
        menuDia.add(menuOficina3);
        menuDia.add(jSeparator3);

        menuTodas.setText("Todas");
        menuTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTodasActionPerformed(evt);
            }
        });
        menuDia.add(menuTodas);

        menuActivacion.add(menuDia);

        menuNoche.setText("Noche");

        menuOficina1Noche.setText("Oficina 1");
        menuOficina1Noche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOficina1NocheActionPerformed(evt);
            }
        });
        menuNoche.add(menuOficina1Noche);

        menuOficina2Noche.setText("Oficina 2");
        menuOficina2Noche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOficina2NocheActionPerformed(evt);
            }
        });
        menuNoche.add(menuOficina2Noche);

        menuOficina3Noche.setText("Oficina 3");
        menuOficina3Noche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOficina3NocheActionPerformed(evt);
            }
        });
        menuNoche.add(menuOficina3Noche);
        menuNoche.add(jSeparator4);

        menuTodasNoches.setText("Todas");
        menuTodasNoches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTodasNochesActionPerformed(evt);
            }
        });
        menuNoche.add(menuTodasNoches);

        menuActivacion.add(menuNoche);
        menuActivacion.add(jSeparator2);

        menuSalir.setText("Salir");
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        menuActivacion.add(menuSalir);

        jMenuBar1.add(menuActivacion);

        menuInfo.setText("Info");

        menuPrincipales.setText("Principales");
        menuPrincipales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPrincipalesActionPerformed(evt);
            }
        });
        menuInfo.add(menuPrincipales);

        menuSecundarias.setText("Secundarias");
        menuSecundarias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSecundariasActionPerformed(evt);
            }
        });
        menuInfo.add(menuSecundarias);

        menuSeguridad.setText("Seguridad");
        menuSeguridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSeguridadActionPerformed(evt);
            }
        });
        menuInfo.add(menuSeguridad);
        menuInfo.add(jSeparator5);

        menuAcercade.setText("Acerca de ...");
        menuAcercade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAcercadeActionPerformed(evt);
            }
        });
        menuInfo.add(menuAcercade);

        jMenuBar1.add(menuInfo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(95, 95, 95))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Evento para apagar todas las luces con el metodo setEnabled.
    private void menuApagarTodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuApagarTodasActionPerformed
        chckPrincipal1.setEnabled(false);
        chckSecundaria1.setEnabled(false);
        chckSeguridad1.setEnabled(false);
        chckPrincipal2.setEnabled(false);
        chckSecundaria2.setEnabled(false);
        chckSeguridad2.setEnabled(false);
        chckPrincipal3.setEnabled(false);
        chckSecundaria3.setEnabled(false);
        chckSeguridad3.setEnabled(false);
        priapagadas = priapagadas + 3;
        seguapagado = seguapagado + 3;
        secunapaga = secunapaga + 3;

    }//GEN-LAST:event_menuApagarTodasActionPerformed
    //Evento para encender todas las luces con el metodo setEnabled.
    private void menuEncenderTodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEncenderTodasActionPerformed
        chckPrincipal1.setEnabled(true);
        chckSecundaria1.setEnabled(true);
        chckSeguridad1.setEnabled(true);
        chckPrincipal2.setEnabled(true);
        chckSecundaria2.setEnabled(true);
        chckSeguridad2.setEnabled(true);
        chckPrincipal3.setEnabled(true);
        chckSecundaria3.setEnabled(true);
        chckSeguridad3.setEnabled(true);
        priapagadas = priapagadas - 3;
        seguapagado = seguapagado - 3;
        secunapaga = secunapaga - 3;


    }//GEN-LAST:event_menuEncenderTodasActionPerformed
    //Evento para encender principal y secundaria de la oficina 1-
    private void menuOficina1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOficina1ActionPerformed
        chckPrincipal1.setEnabled(true);
        chckSecundaria1.setEnabled(true);
        chckSeguridad1.setEnabled(false);

    }//GEN-LAST:event_menuOficina1ActionPerformed
    //Evento para encender principal y secundaria de la oficina 2
    private void menuOficina2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOficina2ActionPerformed
        chckPrincipal2.setEnabled(true);
        chckSecundaria2.setEnabled(true);
        chckSeguridad2.setEnabled(false);
    }//GEN-LAST:event_menuOficina2ActionPerformed
    //Evento para encender principal y secundaria de la oficina 3
    private void menuOficina3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOficina3ActionPerformed
        chckPrincipal3.setEnabled(true);
        chckSecundaria3.setEnabled(true);
        chckSeguridad3.setEnabled(false);
    }//GEN-LAST:event_menuOficina3ActionPerformed
    //Evento de para encender todas las luces principales y secundarias.
    private void menuTodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTodasActionPerformed
        chckPrincipal1.setEnabled(true);
        chckSecundaria1.setEnabled(true);
        chckSeguridad1.setEnabled(false);
        chckPrincipal2.setEnabled(true);
        chckSecundaria2.setEnabled(true);
        chckSeguridad2.setEnabled(false);
        chckPrincipal3.setEnabled(true);
        chckSecundaria3.setEnabled(true);
        chckSeguridad3.setEnabled(false);
    }//GEN-LAST:event_menuTodasActionPerformed
    //Evento para solo activar las luces de seguridad de la oficina 1.
    private void menuOficina1NocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOficina1NocheActionPerformed
        chckPrincipal1.setEnabled(false);
        chckSecundaria1.setEnabled(false);
        chckSeguridad1.setEnabled(true);
    }//GEN-LAST:event_menuOficina1NocheActionPerformed
    //Evento para solo activar las luces de seguridad de la oficina 2.
    private void menuOficina2NocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOficina2NocheActionPerformed
        chckPrincipal2.setEnabled(false);
        chckSecundaria2.setEnabled(false);
        chckSeguridad2.setEnabled(true);
    }//GEN-LAST:event_menuOficina2NocheActionPerformed
    //Evento para solo activar las luces de seguridad de la oficina 2.
    private void menuOficina3NocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOficina3NocheActionPerformed
        chckPrincipal3.setEnabled(false);
        chckSecundaria3.setEnabled(false);
        chckSeguridad3.setEnabled(true);
    }//GEN-LAST:event_menuOficina3NocheActionPerformed
    //Evento para solo activar toodas las luces de seguridad de todas las oficinas.
    private void menuTodasNochesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTodasNochesActionPerformed
        chckPrincipal1.setEnabled(false);
        chckSecundaria1.setEnabled(false);
        chckSeguridad1.setEnabled(true);
        chckPrincipal2.setEnabled(false);
        chckSecundaria2.setEnabled(false);
        chckSeguridad2.setEnabled(true);
        chckPrincipal3.setEnabled(false);
        chckSecundaria3.setEnabled(false);
        chckSeguridad3.setEnabled(true);
    }//GEN-LAST:event_menuTodasNochesActionPerformed
    //Evento de para salir.
    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuSalirActionPerformed
    //Evento que nos indica cuantas luces principales encendidas y apagadas hay.
    private void menuPrincipalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPrincipalesActionPerformed
        JOptionPane.showMessageDialog(null, "Las luces principales encendidas son: " + priencendidas + "\n apagadas son: " + priapagadas);

    }//GEN-LAST:event_menuPrincipalesActionPerformed
    //Evento  que nos indica la informacion del programador.
    private void menuAcercadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAcercadeActionPerformed
        JOptionPane.showMessageDialog(null, "Administracion de luces \nProgramador: Melvin Paul Gonzalez Pascual");
    }//GEN-LAST:event_menuAcercadeActionPerformed
    //Evento que nos indica cuantas luces sececundarias  encendidas y apagadas hay.
    private void menuSecundariasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSecundariasActionPerformed
        JOptionPane.showMessageDialog(null, "Las luces secundarias encendidas son: " + secunencendidas + "\n apagadas son: " + secunapaga);
    }//GEN-LAST:event_menuSecundariasActionPerformed
    //Evento que nos indica cuantas luces principales encendidas y apagadas hay.
    private void menuSeguridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSeguridadActionPerformed
        JOptionPane.showMessageDialog(null, "Las luces de seguridad encendidas son: " + seguencendido + "\n apagadas son: " + seguapagado);
    }//GEN-LAST:event_menuSeguridadActionPerformed
    //Evento del boton para encender todas las luces.
    private void btnEncenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncenderActionPerformed
        chckPrincipal1.setEnabled(true);
        chckSecundaria1.setEnabled(true);
        chckSeguridad1.setEnabled(true);
        chckPrincipal2.setEnabled(true);
        chckSecundaria2.setEnabled(true);
        chckSeguridad2.setEnabled(true);
        chckPrincipal3.setEnabled(true);
        chckSecundaria3.setEnabled(true);
        chckSeguridad3.setEnabled(true);
    }//GEN-LAST:event_btnEncenderActionPerformed
    //Evento del boton para apagar todas las luces.
    private void btnApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarActionPerformed
        chckPrincipal1.setEnabled(false);
        chckSecundaria1.setEnabled(false);
        chckSeguridad1.setEnabled(false);
        chckPrincipal2.setEnabled(false);
        chckSecundaria2.setEnabled(false);
        chckSeguridad2.setEnabled(false);
        chckPrincipal3.setEnabled(false);
        chckSecundaria3.setEnabled(false);
        chckSeguridad3.setEnabled(false);
    }//GEN-LAST:event_btnApagarActionPerformed
    //Evento del boton para encender todas las luces principales y secundarias.
    private void btnDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiaActionPerformed
        chckPrincipal1.setEnabled(true);
        chckSecundaria1.setEnabled(true);
        chckSeguridad1.setEnabled(false);
        chckPrincipal2.setEnabled(true);
        chckSecundaria2.setEnabled(true);
        chckSeguridad2.setEnabled(false);
        chckPrincipal3.setEnabled(true);
        chckSecundaria3.setEnabled(true);
        chckSeguridad3.setEnabled(false);
    }//GEN-LAST:event_btnDiaActionPerformed
    //Evento del boton para encender todas las luces de seguridad.    
    private void btnNocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNocheActionPerformed
        chckPrincipal1.setEnabled(false);
        chckSecundaria1.setEnabled(false);
        chckSeguridad1.setEnabled(true);
        chckPrincipal2.setEnabled(false);
        chckSecundaria2.setEnabled(false);
        chckSeguridad2.setEnabled(true);
        chckPrincipal3.setEnabled(false);
        chckSecundaria3.setEnabled(false);
        chckSeguridad3.setEnabled(true);
    }//GEN-LAST:event_btnNocheActionPerformed
    //Evento que nos indica cuantas luces principales encendidas y apagadas hay.
    private void btnPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrincipalActionPerformed
        JOptionPane.showMessageDialog(null, "Las luces principales encendidas son: " + priencendidas + "\n apagadas son: " + priapagadas);
    }//GEN-LAST:event_btnPrincipalActionPerformed
    //Evento que nos indica cuantas luces secundarias encendidas y apagadas hay.
    private void btnSecundariasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSecundariasActionPerformed
        JOptionPane.showMessageDialog(null, "Las luces secundarias encendidas son: " + secunencendidas + "\n apagadas son: " + secunapaga);
    }//GEN-LAST:event_btnSecundariasActionPerformed
    //Evento que nos indica cuantas luces de seguridad que estan encendidas y apagadas hay.
    private void btnSeguridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeguridadActionPerformed
        JOptionPane.showMessageDialog(null, "Las luces de seguridad encendidas son: " + seguencendido + "\n apagadas son: " + seguapagado);
    }//GEN-LAST:event_btnSeguridadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(oficinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(oficinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(oficinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(oficinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new oficinas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApagar;
    private javax.swing.JButton btnDia;
    private javax.swing.JButton btnEncender;
    private javax.swing.JButton btnNoche;
    private javax.swing.JButton btnPrincipal;
    private javax.swing.JButton btnSecundarias;
    private javax.swing.JButton btnSeguridad;
    private javax.swing.JCheckBox chckPrincipal1;
    private javax.swing.JCheckBox chckPrincipal2;
    private javax.swing.JCheckBox chckPrincipal3;
    private javax.swing.JCheckBox chckSecundaria1;
    private javax.swing.JCheckBox chckSecundaria2;
    private javax.swing.JCheckBox chckSecundaria3;
    private javax.swing.JCheckBox chckSeguridad1;
    private javax.swing.JCheckBox chckSeguridad2;
    private javax.swing.JCheckBox chckSeguridad3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem menuAcercade;
    private javax.swing.JMenu menuActivacion;
    private javax.swing.JMenuItem menuApagarTodas;
    private javax.swing.JMenu menuDia;
    private javax.swing.JMenuItem menuEncenderTodas;
    private javax.swing.JMenu menuInfo;
    private javax.swing.JMenu menuNoche;
    private javax.swing.JMenuItem menuOficina1;
    private javax.swing.JMenuItem menuOficina1Noche;
    private javax.swing.JMenuItem menuOficina2;
    private javax.swing.JMenuItem menuOficina2Noche;
    private javax.swing.JMenuItem menuOficina3;
    private javax.swing.JMenuItem menuOficina3Noche;
    private javax.swing.JMenuItem menuPrincipales;
    private javax.swing.JMenuItem menuSalir;
    private javax.swing.JMenuItem menuSecundarias;
    private javax.swing.JMenuItem menuSeguridad;
    private javax.swing.JMenuItem menuTodas;
    private javax.swing.JMenuItem menuTodasNoches;
    // End of variables declaration//GEN-END:variables
}
