/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lenguaje111213;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Melvin
 */
public class botonessumas extends javax.swing.JFrame {

    /**
     * Creates new form botonessumas
     */
    public botonessumas() {
        initComponents();
        eventos();
    }
    //Metodo para desactivar los botones
    public void desactivarbotones() {
        botonUno.setEnabled(false);
        botonDos.setEnabled(false);
        botonTres.setEnabled(false);
        botonCuatro.setEnabled(false);
        botonCinco.setEnabled(false);
        botonSeis.setEnabled(false);
    }
    //Metodo para activar los botones
    public void activarbotones() {
        botonUno.setEnabled(true);
        botonDos.setEnabled(true);
        botonTres.setEnabled(true);
        botonCuatro.setEnabled(true);
        botonCinco.setEnabled(true);
        botonSeis.setEnabled(true);
    }
    //Metodo para realizar los calculos.
    public void calculos() {
        int total = 0;
        if (botonUno.isSelected()) {
            total = total + 1;
        }
        if (botonDos.isSelected()) {
            total = total + 2;
        }
        if (botonTres.isSelected()) {
            total = total + 3;
        }
        if (botonCuatro.isSelected()) {
            total = total + 4;
        }
        if (botonCinco.isSelected()) {
            total = total + 5;
        }
        if (botonSeis.isSelected()) {
            total = total + 6;
        }
        etiResultado.setText("El total es: "+total);
    }
    //Metodos para crear los eventos necesarios.
    public void eventos() {
        btnActivarTodos.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                btnActivarTodosActionPerformed(evt);
            }
        });
        btnDesactivarTodos.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnDesactivarTodosActionPerformed(evt);
            }
        });
        btnTotal.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnTotalActionPerformed(evt);
            }
        });
    }
    //Evento para activar los botones.
    public void btnActivarTodosActionPerformed(ActionEvent evt) {
        activarbotones();
    }
    //Evento para desactivar los botones.
    public void btnDesactivarTodosActionPerformed(ActionEvent evt) {
        desactivarbotones();
    }
    //Evento para realizar los calculos
    public void btnTotalActionPerformed(ActionEvent evt) {
        calculos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonDos = new javax.swing.JToggleButton();
        botonTres = new javax.swing.JToggleButton();
        botonUno = new javax.swing.JToggleButton();
        botonCinco = new javax.swing.JToggleButton();
        botonSeis = new javax.swing.JToggleButton();
        botonCuatro = new javax.swing.JToggleButton();
        btnDesactivarTodos = new javax.swing.JButton();
        btnActivarTodos = new javax.swing.JButton();
        btnTotal = new javax.swing.JButton();
        etiResultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 255));

        botonDos.setText("2");

        botonTres.setText("3");

        botonUno.setText("1");

        botonCinco.setText("5");

        botonSeis.setText("6");

        botonCuatro.setText("4");

        btnDesactivarTodos.setText("Desactivar Todos");

        btnActivarTodos.setText("Activar Todos");

        btnTotal.setText("Total");

        etiResultado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(etiResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonUno, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonDos, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonTres, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnDesactivarTodos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnActivarTodos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonDos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonTres, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonUno, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnDesactivarTodos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnActivarTodos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(etiResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(botonessumas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(botonessumas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(botonessumas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(botonessumas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new botonessumas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton botonCinco;
    private javax.swing.JToggleButton botonCuatro;
    private javax.swing.JToggleButton botonDos;
    private javax.swing.JToggleButton botonSeis;
    private javax.swing.JToggleButton botonTres;
    private javax.swing.JToggleButton botonUno;
    private javax.swing.JButton btnActivarTodos;
    private javax.swing.JButton btnDesactivarTodos;
    private javax.swing.JButton btnTotal;
    private javax.swing.JLabel etiResultado;
    // End of variables declaration//GEN-END:variables
}
