/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paqueteprincipal;

/**
 *
 * @author Melvin
 */
import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ClientesTabla extends javax.swing.JFrame {
    //Variables globales para el programa.
    Connection conexion;
    Statement sentencia;
    DefaultTableModel modelo;

    /**
     * Creates new form ClientesTabla
     */
    //Se preparan los datos para poder ejecutar los metodos creados.
    public ClientesTabla() {
        initComponents();
        PrepararBaseDatos();
        PrepararTabla();
        MostrarClientes();
    }
    //Se crea el metodo para preparar la base de datos.
    void PrepararBaseDatos() {
        try {
            String controlador = "org.postgresql.Driver";
            Class.forName(controlador).newInstance();
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException e) {
            JOptionPane.showMessageDialog(null, "Error al cargar el controlador");
        }
        try {
            String DSN = "jdbc:postgresql://localhost:5432/BDTap?currentSchema=manempsa";
            //jdbc:postgresql://localhost:5432/mydatabase?currentSchema=myschema
            String user = "postgres";
            String password = "melvin";
            conexion = DriverManager.getConnection(DSN, user, password);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al realizar la conexion");
        }
        try {
            sentencia = conexion.createStatement(
                    ResultSet.TYPE_SCROLL_INSENSITIVE,
                    ResultSet.CONCUR_READ_ONLY);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al crear el objeto sentencia");
        }

    }
    //Metodo para generar la tabla.
    void PrepararTabla() {
        String titulos[] = new String[5];
        modelo = new DefaultTableModel(null, titulos);
        jTabla.setModel(modelo);
    }
    //Metodo para ver los clientes en la tabla creada.
    void MostrarClientes() {
        try {
            ResultSet r = sentencia.executeQuery("select * from cliente");
            //Se agreanga los datos del cliente.
            String titulos[] = {"CIF", "Nombre", "Direccion", "Telefono 1", "Telefono 2"};
            modelo = new DefaultTableModel(null, titulos);
            String fila[] = new String[5];
            while (r.next()) {
                fila[0] = r.getString("cif");
                fila[1] = r.getString("nombre");
                fila[2] = r.getString("direccion");
                fila[3] = r.getString("telefono1");
                fila[4] = r.getString("telefono2");
                modelo.addRow(fila);
            }
            jTabla.setModel(modelo);
            HacerCalculos(r);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al extraer los datos de la tabla");
        }
    }
    //Metodo para hacer el calculos de empleados mostrados en la tabla.    
    void HacerCalculos(ResultSet r){
        int ntrab=0;
        try {
            r.beforeFirst();
            while(r.next()){
                ntrab++;
            }
            etiNumeroClientes.setText(""+ntrab);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al realizar cálculos");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogoNuevo = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNuevoCIF = new javax.swing.JTextField();
        txtNuevoNombre = new javax.swing.JTextField();
        txtNuevoDireccion = new javax.swing.JTextField();
        txtNuevoTelefono1 = new javax.swing.JTextField();
        txtNuevoTelefono2 = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        dialogoModificar = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtModCIF = new javax.swing.JTextField();
        txtModNombre = new javax.swing.JTextField();
        txtModDireccion = new javax.swing.JTextField();
        txtModTelefono1 = new javax.swing.JTextField();
        txtModTelefono2 = new javax.swing.JTextField();
        btnModAceptar = new javax.swing.JButton();
        btnModCancelar = new javax.swing.JButton();
        dialogoFiltrar = new javax.swing.JDialog();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtFiltrarCIF = new javax.swing.JTextField();
        txtFiltrarNombre = new javax.swing.JTextField();
        txtFiltrarDireccion = new javax.swing.JTextField();
        txtFiltrarTelefono1 = new javax.swing.JTextField();
        txtFiltrarTelefono2 = new javax.swing.JTextField();
        btnFiltrarAceptar = new javax.swing.JButton();
        btnFiltrarCancelar = new javax.swing.JButton();
        btnFiltrarVerTodos = new javax.swing.JButton();
        panelOrdenacion = new javax.swing.JPanel();
        cboCamposOrdenacion = new javax.swing.JComboBox<>();
        radioASC = new javax.swing.JRadioButton();
        radioDESC = new javax.swing.JRadioButton();
        grupoOrdenacion = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabla = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnEliminar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnFiltrar = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        etiNumeroClientes = new javax.swing.JLabel();

        jLabel1.setText("Añadir Nuevo Cliente");

        jLabel2.setText("CIF:");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Direccion:");

        jLabel5.setText("Telefono 1:");

        jLabel6.setText("Telefono 2:");

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogoNuevoLayout = new javax.swing.GroupLayout(dialogoNuevo.getContentPane());
        dialogoNuevo.getContentPane().setLayout(dialogoNuevoLayout);
        dialogoNuevoLayout.setHorizontalGroup(
            dialogoNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoNuevoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogoNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(dialogoNuevoLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtNuevoTelefono1))
                    .addGroup(dialogoNuevoLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txtNuevoTelefono2))
                    .addGroup(dialogoNuevoLayout.createSequentialGroup()
                        .addGroup(dialogoNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(27, 27, 27)
                        .addGroup(dialogoNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNuevoCIF)
                            .addComponent(txtNuevoNombre)
                            .addComponent(txtNuevoDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)))
                    .addGroup(dialogoNuevoLayout.createSequentialGroup()
                        .addComponent(btnAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addComponent(btnCancelar)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        dialogoNuevoLayout.setVerticalGroup(
            dialogoNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoNuevoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(dialogoNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNuevoCIF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogoNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNuevoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogoNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtNuevoDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogoNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNuevoTelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogoNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNuevoTelefono2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(dialogoNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel7.setText("Modificar Cliente");

        jLabel8.setText("CIF:");

        jLabel9.setText("Nombre:");

        jLabel10.setText("Direccion:");

        jLabel11.setText("Telefono 1:");

        jLabel12.setText("Telefono 2:");

        txtModCIF.setEnabled(false);

        btnModAceptar.setText("Aceptar");
        btnModAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModAceptarActionPerformed(evt);
            }
        });

        btnModCancelar.setText("Cancelar");
        btnModCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogoModificarLayout = new javax.swing.GroupLayout(dialogoModificar.getContentPane());
        dialogoModificar.getContentPane().setLayout(dialogoModificarLayout);
        dialogoModificarLayout.setHorizontalGroup(
            dialogoModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoModificarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogoModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7)
                    .addGroup(dialogoModificarLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(txtModTelefono1))
                    .addGroup(dialogoModificarLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(txtModTelefono2))
                    .addGroup(dialogoModificarLayout.createSequentialGroup()
                        .addGroup(dialogoModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(27, 27, 27)
                        .addGroup(dialogoModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtModCIF)
                            .addComponent(txtModNombre)
                            .addComponent(txtModDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)))
                    .addGroup(dialogoModificarLayout.createSequentialGroup()
                        .addComponent(btnModAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addComponent(btnModCancelar)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        dialogoModificarLayout.setVerticalGroup(
            dialogoModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoModificarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(dialogoModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtModCIF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogoModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtModNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogoModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(txtModDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogoModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtModTelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogoModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtModTelefono2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(dialogoModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModAceptar)
                    .addComponent(btnModCancelar))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel13.setText("Filtrado de Clientes");

        jLabel14.setText("CIF:");

        jLabel15.setText("Nombre:");

        jLabel16.setText("Direccion:");

        jLabel17.setText("Telefono 1:");

        jLabel18.setText("Telefono 2:");

        btnFiltrarAceptar.setText("Aceptar");
        btnFiltrarAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarAceptarActionPerformed(evt);
            }
        });

        btnFiltrarCancelar.setText("Cancelar");
        btnFiltrarCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarCancelarActionPerformed(evt);
            }
        });

        btnFiltrarVerTodos.setText("Ver Todos");
        btnFiltrarVerTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarVerTodosActionPerformed(evt);
            }
        });

        panelOrdenacion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ordenación", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 204))); // NOI18N

        cboCamposOrdenacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "cif", "nombre", "direccion", "telefono1", "telefono2" }));

        grupoOrdenacion.add(radioASC);
        radioASC.setText("ASC");

        grupoOrdenacion.add(radioDESC);
        radioDESC.setText("DESC");

        javax.swing.GroupLayout panelOrdenacionLayout = new javax.swing.GroupLayout(panelOrdenacion);
        panelOrdenacion.setLayout(panelOrdenacionLayout);
        panelOrdenacionLayout.setHorizontalGroup(
            panelOrdenacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOrdenacionLayout.createSequentialGroup()
                .addComponent(cboCamposOrdenacion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelOrdenacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(radioDESC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(radioASC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29))
        );
        panelOrdenacionLayout.setVerticalGroup(
            panelOrdenacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOrdenacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelOrdenacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboCamposOrdenacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioASC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioDESC)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dialogoFiltrarLayout = new javax.swing.GroupLayout(dialogoFiltrar.getContentPane());
        dialogoFiltrar.getContentPane().setLayout(dialogoFiltrarLayout);
        dialogoFiltrarLayout.setHorizontalGroup(
            dialogoFiltrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoFiltrarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogoFiltrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogoFiltrarLayout.createSequentialGroup()
                        .addGroup(dialogoFiltrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addGroup(dialogoFiltrarLayout.createSequentialGroup()
                                .addGroup(dialogoFiltrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16))
                                .addGap(27, 27, 27)
                                .addGroup(dialogoFiltrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtFiltrarNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                                    .addComponent(txtFiltrarCIF))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(dialogoFiltrarLayout.createSequentialGroup()
                        .addGroup(dialogoFiltrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtFiltrarDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(dialogoFiltrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(dialogoFiltrarLayout.createSequentialGroup()
                                    .addComponent(jLabel17)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtFiltrarTelefono1))
                                .addGroup(dialogoFiltrarLayout.createSequentialGroup()
                                    .addComponent(jLabel18)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtFiltrarTelefono2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(dialogoFiltrarLayout.createSequentialGroup()
                                    .addComponent(btnFiltrarAceptar)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnFiltrarVerTodos)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnFiltrarCancelar))
                                .addComponent(panelOrdenacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 22, Short.MAX_VALUE))))
        );
        dialogoFiltrarLayout.setVerticalGroup(
            dialogoFiltrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoFiltrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(dialogoFiltrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtFiltrarCIF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogoFiltrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtFiltrarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogoFiltrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(txtFiltrarDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogoFiltrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtFiltrarTelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogoFiltrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtFiltrarTelefono2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(panelOrdenacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogoFiltrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogoFiltrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnFiltrarAceptar)
                        .addComponent(btnFiltrarCancelar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogoFiltrarLayout.createSequentialGroup()
                        .addComponent(btnFiltrarVerTodos)
                        .addContainerGap())))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTabla);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Acciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 204))); // NOI18N

        btnEliminar.setText("Eliminar Cliente");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo Cliente");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar Cliente");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnFiltrar.setText("Filtrar");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnEliminar)
                .addGap(18, 18, 18)
                .addComponent(btnNuevo)
                .addGap(18, 18, 18)
                .addComponent(btnModificar)
                .addGap(18, 18, 18)
                .addComponent(btnFiltrar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar)
                    .addComponent(btnNuevo)
                    .addComponent(btnModificar)
                    .addComponent(btnFiltrar))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jLabel19.setText("N° Clientes: ");

        etiNumeroClientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(etiNumeroClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(etiNumeroClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Evento para finalizar la conexion con la base de datos.
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            conexion.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "No se pudo cerrar la base de datos");
        }
    }//GEN-LAST:event_formWindowClosing
    //Evento para elimanar un cliente.
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int filsel;
        String cif;
        int resp;
        try {
            filsel = jTabla.getSelectedRow();
            if (filsel == -1) {
                JOptionPane.showMessageDialog(null, "Debes seleccionar el trabajador a borrar");
            } else {
                resp = JOptionPane.showConfirmDialog(null, "¿Desea eliminar el trabajador seleccionado?", "Eliminar", JOptionPane.YES_NO_OPTION);
                if (resp == JOptionPane.YES_OPTION) {
                    modelo = (DefaultTableModel) jTabla.getModel();
                    cif = (String) modelo.getValueAt(filsel, 0);
                    sentencia.executeUpdate("delete from cliente where cif='" + cif + "'");
                    MostrarClientes();
                }
            }
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al eliminar cliente");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed
    //Evento para abrir un panel para la actualizacion de datos.
    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        dialogoNuevo.setSize(300, 400);
        dialogoNuevo.setModal(true);
        dialogoNuevo.setVisible(true);
        MostrarClientes();
    }//GEN-LAST:event_btnNuevoActionPerformed
    //Evento para cerrar el panel correspondiente.
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dialogoNuevo.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed
    //Evento para aceptar la agregacion de un nuevo cliente.
    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        String cfi, nombre, direccion, telefono1, telefono2;
        String sql;
        try {
            cfi = txtNuevoCIF.getText();
            nombre = txtNuevoNombre.getText();
            direccion = txtNuevoDireccion.getText();
            telefono1 = txtNuevoTelefono1.getText();
            telefono2 = txtNuevoTelefono2.getText();

            sql = "insert into cliente values ('" + cfi + "','" + nombre + "','" + direccion + "','" + telefono1 + "','" + telefono2 + "')";
            sentencia.executeUpdate(sql);
            dialogoNuevo.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al introducir al nuevo cliente");
        }
    }//GEN-LAST:event_btnAceptarActionPerformed
    //Evento para modificar la informacion de un cliente.
    private void btnModAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModAceptarActionPerformed
        
        String cif,nombre,direccion,telefono1,telefono2;
        String sql;
        try {
            cif=txtModCIF.getText();
            nombre=txtModNombre.getText();
            direccion=txtModDireccion.getText();
            telefono1=txtModTelefono1.getText();
            telefono2=txtModTelefono2.getText();
            sql="update cliente set nombre='"+nombre+"',"+"direccion='"+direccion+"',"+"telefono1='"
                    +telefono1+"',"+"telefono2='"+telefono2+"' where cif='"+cif+"'";
            sentencia.executeUpdate(sql);
            dialogoModificar.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al modificar el cliente");
        }        
    }//GEN-LAST:event_btnModAceptarActionPerformed
    //Para cancelar y salir del panel
    private void btnModCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModCancelarActionPerformed
        dialogoModificar.dispose();
    }//GEN-LAST:event_btnModCancelarActionPerformed
    //Evento para seleccionar y modificar los datos de un cliente, el cual los manda al panel.
    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        int fsel;
        String CIF, nombre, direccion, telefono1, telefono2;
        fsel = jTabla.getSelectedRow();
        if (fsel == -1) {
            JOptionPane.showMessageDialog(null, "Debes seleccionar el cliente a modificar");
        } else {
            modelo = (DefaultTableModel) jTabla.getModel();
            CIF = (String) modelo.getValueAt(fsel, 0);
            nombre = (String) modelo.getValueAt(fsel, 1);
            direccion = (String) modelo.getValueAt(fsel, 2);
            telefono1 = (String) modelo.getValueAt(fsel, 3);
            telefono2 = (String) modelo.getValueAt(fsel, 4);
            txtModCIF.setText(CIF);
            txtModNombre.setText(nombre);
            txtModDireccion.setText(direccion);
            txtModTelefono1.setText(telefono1);
            txtModTelefono2.setText(telefono2);
            dialogoModificar.setSize(300, 400);
            dialogoModificar.setModal(true);
            dialogoModificar.setVisible(true);
            MostrarClientes();

        }
    }//GEN-LAST:event_btnModificarActionPerformed
    //Boton para hacer los filtros ademas de buscar los datos del cliente.
    private void btnFiltrarAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarAceptarActionPerformed
        String cif,nombre,direccion,telefono1,telefono2;
        String sql;
        int ncond=0;
        try{
        cif=txtFiltrarCIF.getText();
        nombre=txtFiltrarNombre.getText();
        direccion=txtFiltrarDireccion.getText();
        telefono1=txtFiltrarTelefono1.getText();
        telefono2=txtFiltrarTelefono2.getText();
        
        sql="select * from cliente";
        if(!cif.equals("")){
            ncond++;
            sql+=" where dni like '%"+cif+"%' ";
        }
        if(!nombre.equals("")){
            ncond++;
            if(ncond==1){
                sql+=" where nombre like '%"+nombre+"%' ";
            }else{
                sql+=" and nombre like '%"+nombre+"%' ";
            }
        }
        if(!direccion.equals("")){
            ncond++;
            if(ncond==1){
                sql+=" where direccion like '%"+direccion+"%' ";
            }else{
                sql+=" and direccion like '%"+direccion+"%' ";
            }
        }
        if(!telefono1.equals("")){
            ncond++;
            if(ncond==1){
                sql+=" where telefono1 like '%"+telefono1+"%' ";
            }else{
                sql+=" and telefono1 like '%"+telefono1+"%' ";
            }
        }
        if(!telefono2.equals("")){
            ncond++;
            if(ncond==1){
                sql+=" where telefono2 like '%"+telefono2+"%' ";
            }else{
                sql+=" and telefono2 like '%"+telefono2+"%' ";
            }
        }
        //Ordenacion de los resultados o de la tabla.
        String campoorden=(String) cboCamposOrdenacion.getSelectedItem();
        if(!campoorden.equals("(Sin ordenacion)")){
            if(radioASC.isSelected()){
                sql+=" order by "+campoorden+ " asc";
            }else{
                sql+=" order by "+campoorden+ " desc";
            }
        }
        
        ResultSet r=sentencia.executeQuery(sql);
        String titulos[]={"CIF","Nombre","Direccion","Telefono 1","Telefono 2"};
        modelo=new DefaultTableModel(null,titulos);
        String fila[]=new String [5];
        while(r.next()){
        fila[0] = r.getString("cif");
                fila[1] = r.getString("nombre");
                fila[2] = r.getString("direccion");
                fila[3] = r.getString("telefono1");
                fila[4] = r.getString("telefono2");
                modelo.addRow(fila);
        }
        jTabla.setModel(modelo);
        HacerCalculos(r);
        dialogoFiltrar.dispose();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error al filtrar la tabla clientes");
    }
    }//GEN-LAST:event_btnFiltrarAceptarActionPerformed
    //Cerrar el panel
    private void btnFiltrarCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarCancelarActionPerformed
        dialogoFiltrar.dispose();
    }//GEN-LAST:event_btnFiltrarCancelarActionPerformed
    //Crea un nuevo panel
    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        dialogoFiltrar.setSize(300,400);
        dialogoFiltrar.setModal(true);
        dialogoFiltrar.setVisible(true);
    }//GEN-LAST:event_btnFiltrarActionPerformed
    //Muuestra los clientes en las tablas.
    private void btnFiltrarVerTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarVerTodosActionPerformed
        MostrarClientes();
        dialogoFiltrar.dispose();
    }//GEN-LAST:event_btnFiltrarVerTodosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientesTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientesTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientesTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientesTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientesTabla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnFiltrarAceptar;
    private javax.swing.JButton btnFiltrarCancelar;
    private javax.swing.JButton btnFiltrarVerTodos;
    private javax.swing.JButton btnModAceptar;
    private javax.swing.JButton btnModCancelar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<String> cboCamposOrdenacion;
    private javax.swing.JDialog dialogoFiltrar;
    private javax.swing.JDialog dialogoModificar;
    private javax.swing.JDialog dialogoNuevo;
    private javax.swing.JLabel etiNumeroClientes;
    private javax.swing.ButtonGroup grupoOrdenacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabla;
    private javax.swing.JPanel panelOrdenacion;
    private javax.swing.JRadioButton radioASC;
    private javax.swing.JRadioButton radioDESC;
    private javax.swing.JTextField txtFiltrarCIF;
    private javax.swing.JTextField txtFiltrarDireccion;
    private javax.swing.JTextField txtFiltrarNombre;
    private javax.swing.JTextField txtFiltrarTelefono1;
    private javax.swing.JTextField txtFiltrarTelefono2;
    private javax.swing.JTextField txtModCIF;
    private javax.swing.JTextField txtModDireccion;
    private javax.swing.JTextField txtModNombre;
    private javax.swing.JTextField txtModTelefono1;
    private javax.swing.JTextField txtModTelefono2;
    private javax.swing.JTextField txtNuevoCIF;
    private javax.swing.JTextField txtNuevoDireccion;
    private javax.swing.JTextField txtNuevoNombre;
    private javax.swing.JTextField txtNuevoTelefono1;
    private javax.swing.JTextField txtNuevoTelefono2;
    // End of variables declaration//GEN-END:variables
}
