/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lenguaje345;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Melvin
 */
public class analizar3 extends javax.swing.JFrame {

    /**
     * Creates new form analizar3
     */
    public analizar3() {
        initComponents();
    }
    //Metodo para la busqueda
    public void cadenas(){
    //Si esta vacio no se realiza ninguna opcion.    
    if(txtFrase.getText().length()==0){
     JOptionPane.showMessageDialog(rootPane, "Ingrense Datos");
    }else{  
    //Se crean varias cadenas.    
    String cad1=txtFrase.getText();
    String cad2=txtPalabra1.getText();
    String cad3=txtPalabra2.getText();
    String cad4=txtPalabra3.getText();
    String cad5=txtPalabra4.getText();
    //Condicion para ver si es igual
    if(cad1.equals(cad2)){
        etiPalabra1.setText("La palabra es igual a la frase");
        }else{
        etiPalabra1.setText("La palabra no es igual");}
    //Condicion para ver si es comienza
    if(cad1.startsWith(cad3)){
        etiPalabra2.setText("Si comienza");
    }else{
        etiPalabra2.setText("No empieza "); }
    //Condicion para ver si termina
    if(cad1.endsWith(cad4)){
        etiPalabra3.setText("Si termina");
    }else{
        etiPalabra3.setText("No termina ");
    }
    //Condicion para ver si contiene esa palabra
    if( cad1.contains(cad5)){
    etiPalabra4.setText("Encontrado en la posición: "+cad1.indexOf(cad5));
    }else{etiPalabra4.setText("No se encontro");}
    }
    }
    //Metodo para validar el teclado.
    public void verif(KeyEvent evt){
    char validar = evt.getKeyChar();
        if(Character.isDigit(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingrese solo letras");
        }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFrase = new javax.swing.JTextField();
        txtPalabra1 = new javax.swing.JTextField();
        txtPalabra2 = new javax.swing.JTextField();
        txtPalabra3 = new javax.swing.JTextField();
        txtPalabra4 = new javax.swing.JTextField();
        etiPalabra1 = new javax.swing.JLabel();
        etiPalabra2 = new javax.swing.JLabel();
        etiPalabra3 = new javax.swing.JLabel();
        etiPalabra4 = new javax.swing.JLabel();
        btnAnalizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtFrase.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFraseKeyTyped(evt);
            }
        });

        txtPalabra1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPalabra1KeyTyped(evt);
            }
        });

        txtPalabra2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPalabra2KeyTyped(evt);
            }
        });

        txtPalabra3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPalabra3KeyTyped(evt);
            }
        });

        txtPalabra4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPalabra4KeyTyped(evt);
            }
        });

        btnAnalizar.setText("Analizar");
        btnAnalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtFrase)
                    .addComponent(txtPalabra1)
                    .addComponent(txtPalabra2)
                    .addComponent(txtPalabra3)
                    .addComponent(txtPalabra4)
                    .addComponent(etiPalabra1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiPalabra2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiPalabra3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiPalabra4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAnalizar, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtFrase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPalabra1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPalabra2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPalabra3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPalabra4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(etiPalabra1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiPalabra2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(etiPalabra3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiPalabra4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAnalizar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Evento del metodo.
    private void btnAnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalizarActionPerformed
    cadenas();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAnalizarActionPerformed
    //Eventos de validacion
    private void txtFraseKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFraseKeyTyped
        verif(evt);
    }//GEN-LAST:event_txtFraseKeyTyped

    private void txtPalabra1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPalabra1KeyTyped
        verif(evt);
    }//GEN-LAST:event_txtPalabra1KeyTyped

    private void txtPalabra2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPalabra2KeyTyped
        verif(evt);
    }//GEN-LAST:event_txtPalabra2KeyTyped

    private void txtPalabra3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPalabra3KeyTyped
        verif(evt);
    }//GEN-LAST:event_txtPalabra3KeyTyped

    private void txtPalabra4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPalabra4KeyTyped
        verif(evt);
    }//GEN-LAST:event_txtPalabra4KeyTyped
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(analizar3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(analizar3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(analizar3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(analizar3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new analizar3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalizar;
    private javax.swing.JLabel etiPalabra1;
    private javax.swing.JLabel etiPalabra2;
    private javax.swing.JLabel etiPalabra3;
    private javax.swing.JLabel etiPalabra4;
    private javax.swing.JTextField txtFrase;
    private javax.swing.JTextField txtPalabra1;
    private javax.swing.JTextField txtPalabra2;
    private javax.swing.JTextField txtPalabra3;
    private javax.swing.JTextField txtPalabra4;
    // End of variables declaration//GEN-END:variables
}
