/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lenguajejava;

import java.awt.Toolkit;

/**
 *
 * @author Melvin
 */
public class cuadrodedialogo1 extends javax.swing.JFrame {

    /**
     * Creates new form cuadrodedialogo1
     */
    public cuadrodedialogo1() {
        initComponents();
        
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogCosteInstalacion = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCopiasSimplificada = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCopiasCompleta = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        dialogCosteFormacion = new javax.swing.JDialog();
        jLabel9 = new javax.swing.JLabel();
        txtNAlumnos = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtNHoras = new javax.swing.JTextField();
        btnAceptarFormacion = new javax.swing.JButton();
        btnCancelarFormacion = new javax.swing.JButton();
        dialogCosteMantenimiento = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        btpAnual = new javax.swing.JRadioButton();
        btpSemestral = new javax.swing.JRadioButton();
        btpPuesta = new javax.swing.JRadioButton();
        btnAceptarMantenimiento = new javax.swing.JButton();
        btnCancelarMantenimiento = new javax.swing.JButton();
        grupoMantenimento = new javax.swing.ButtonGroup();
        dialogInfo = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        btnCerrar = new javax.swing.JButton();
        dialogoPres = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCosteInstalacion = new javax.swing.JTextField();
        txtCosteFormacion = new javax.swing.JTextField();
        txtCosteMantenimiento = new javax.swing.JTextField();
        btnCosteInstalacion = new javax.swing.JButton();
        btnCosteFormacion = new javax.swing.JButton();
        btnCosteMantenimiento = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        etiTotal = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        btnInfo = new javax.swing.JButton();

        dialogCosteInstalacion.setTitle("Coste Instalación");
        dialogCosteInstalacion.setMinimumSize(new java.awt.Dimension(300, 200));
        dialogCosteInstalacion.setModal(true);
        dialogCosteInstalacion.setPreferredSize(new java.awt.Dimension(300, 200));

        jLabel5.setText("Versión simplificada:");

        jLabel6.setText("N° de Copias:");

        jLabel7.setText("Versión completa:");

        jLabel8.setText("N° de Copias:");

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogCosteInstalacionLayout = new javax.swing.GroupLayout(dialogCosteInstalacion.getContentPane());
        dialogCosteInstalacion.getContentPane().setLayout(dialogCosteInstalacionLayout);
        dialogCosteInstalacionLayout.setHorizontalGroup(
            dialogCosteInstalacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogCosteInstalacionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(dialogCosteInstalacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addGroup(dialogCosteInstalacionLayout.createSequentialGroup()
                        .addGroup(dialogCosteInstalacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addGap(35, 35, 35)
                        .addGroup(dialogCosteInstalacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCopiasCompleta, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCopiasSimplificada))))
                .addGap(18, 18, 18)
                .addGroup(dialogCosteInstalacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        dialogCosteInstalacionLayout.setVerticalGroup(
            dialogCosteInstalacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogCosteInstalacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogCosteInstalacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(dialogCosteInstalacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogCosteInstalacionLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnCancelar))
                    .addGroup(dialogCosteInstalacionLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dialogCosteInstalacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtCopiasSimplificada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dialogCosteInstalacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtCopiasCompleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        dialogCosteFormacion.setTitle("Coste de Formación");
        dialogCosteFormacion.setMinimumSize(new java.awt.Dimension(250, 170));
        dialogCosteFormacion.setModal(true);

        jLabel9.setText("Número de alumnos:");

        jLabel10.setText("Número de horas:");

        btnAceptarFormacion.setText("Aceptar");
        btnAceptarFormacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarFormacionActionPerformed(evt);
            }
        });

        btnCancelarFormacion.setText("Cancelar");
        btnCancelarFormacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarFormacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogCosteFormacionLayout = new javax.swing.GroupLayout(dialogCosteFormacion.getContentPane());
        dialogCosteFormacion.getContentPane().setLayout(dialogCosteFormacionLayout);
        dialogCosteFormacionLayout.setHorizontalGroup(
            dialogCosteFormacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogCosteFormacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogCosteFormacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(dialogCosteFormacionLayout.createSequentialGroup()
                        .addGroup(dialogCosteFormacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(dialogCosteFormacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNAlumnos, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(txtNHoras)))
                    .addGroup(dialogCosteFormacionLayout.createSequentialGroup()
                        .addComponent(btnAceptarFormacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(btnCancelarFormacion)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        dialogCosteFormacionLayout.setVerticalGroup(
            dialogCosteFormacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogCosteFormacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogCosteFormacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtNAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dialogCosteFormacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtNHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dialogCosteFormacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptarFormacion)
                    .addComponent(btnCancelarFormacion))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        dialogCosteMantenimiento.setTitle("Coste de Mantenimiento");
        dialogCosteMantenimiento.setMinimumSize(new java.awt.Dimension(300, 220));
        dialogCosteMantenimiento.setModal(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones de Mantenimiento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 153))); // NOI18N

        grupoMantenimento.add(btpAnual);
        btpAnual.setText("Anual");

        grupoMantenimento.add(btpSemestral);
        btpSemestral.setText("Semestral");

        grupoMantenimento.add(btpPuesta);
        btpPuesta.setText("Puesta en Funcionamiento");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btpAnual)
                    .addComponent(btpSemestral)
                    .addComponent(btpPuesta))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btpAnual)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btpSemestral)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btpPuesta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnAceptarMantenimiento.setText("Aceptar");
        btnAceptarMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarMantenimientoActionPerformed(evt);
            }
        });

        btnCancelarMantenimiento.setText("Cancelar");
        btnCancelarMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarMantenimientoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogCosteMantenimientoLayout = new javax.swing.GroupLayout(dialogCosteMantenimiento.getContentPane());
        dialogCosteMantenimiento.getContentPane().setLayout(dialogCosteMantenimientoLayout);
        dialogCosteMantenimientoLayout.setHorizontalGroup(
            dialogCosteMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogCosteMantenimientoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(dialogCosteMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(dialogCosteMantenimientoLayout.createSequentialGroup()
                        .addComponent(btnAceptarMantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelarMantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        dialogCosteMantenimientoLayout.setVerticalGroup(
            dialogCosteMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogCosteMantenimientoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogCosteMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptarMantenimiento)
                    .addComponent(btnCancelarMantenimiento))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        dialogInfo.setMinimumSize(new java.awt.Dimension(450, 300));

        jTextPane1.setText("CÁLCULO DE COSTES\n\nHerramienta de apoyo para el cálculo de costes de implantación de software.\n\n-Use el cuadro de texto Coste de Instalación para introducir directamente el coste de instalación del software, o bien pulse el botón asociado para calcular dicho coste.\n\n-Use el cuadro de texto Coste de Formación o su botón asociado para introducir el coste de formación de los empleados.\n\n-Use el cuadro de texto de Coste de Mantenimiento o su botón asociado para introducir el coste de mantenimiento del software.");
        jScrollPane1.setViewportView(jTextPane1);

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogInfoLayout = new javax.swing.GroupLayout(dialogInfo.getContentPane());
        dialogInfo.getContentPane().setLayout(dialogInfoLayout);
        dialogInfoLayout.setHorizontalGroup(
            dialogInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(dialogInfoLayout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(btnCerrar)
                .addContainerGap(176, Short.MAX_VALUE))
        );
        dialogInfoLayout.setVerticalGroup(
            dialogInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCerrar)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        dialogoPres.setMinimumSize(new java.awt.Dimension(400, 212));
        dialogoPres.setUndecorated(true);
        dialogoPres.setPreferredSize(new java.awt.Dimension(400, 212));
        dialogoPres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dialogoPresMouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel11.setText("Programa para Costes");

        javax.swing.GroupLayout dialogoPresLayout = new javax.swing.GroupLayout(dialogoPres.getContentPane());
        dialogoPres.getContentPane().setLayout(dialogoPresLayout);
        dialogoPresLayout.setHorizontalGroup(
            dialogoPresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoPresLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel11)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        dialogoPresLayout.setVerticalGroup(
            dialogoPresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoPresLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel11)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Coste de instalación:");

        jLabel2.setText("Coste de formación:");

        jLabel3.setText("Coste de mantenimiento:");

        txtCosteInstalacion.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCosteInstalacion.setText("0");

        txtCosteFormacion.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCosteFormacion.setText("0");

        txtCosteMantenimiento.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCosteMantenimiento.setText("0");

        btnCosteInstalacion.setText("...");
        btnCosteInstalacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCosteInstalacionActionPerformed(evt);
            }
        });

        btnCosteFormacion.setText("...");
        btnCosteFormacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCosteFormacionActionPerformed(evt);
            }
        });

        btnCosteMantenimiento.setText("...");
        btnCosteMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCosteMantenimientoActionPerformed(evt);
            }
        });

        jLabel4.setText("TOTAL:");

        etiTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        btnInfo.setText("?");
        btnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCosteInstalacion, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                    .addComponent(txtCosteFormacion)
                    .addComponent(txtCosteMantenimiento)
                    .addComponent(etiTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(btnCosteMantenimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCosteFormacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCosteInstalacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCosteInstalacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCosteInstalacion))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCosteFormacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCosteFormacion))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCosteMantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCosteMantenimiento))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnInfo)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Boton para activar el Cuadro de Dialogo Correspondiente.
    private void btnCosteInstalacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCosteInstalacionActionPerformed
        dialogCosteInstalacion.setVisible(true);
    }//GEN-LAST:event_btnCosteInstalacionActionPerformed
    //Boton para activar el Cuadro de Dialogo Correspondiente.
    private void btnCosteFormacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCosteFormacionActionPerformed
        dialogCosteFormacion.setVisible(true);
    }//GEN-LAST:event_btnCosteFormacionActionPerformed
    //Boton para activar el Cuadro de Dialogo Correspondiente.
    private void btnCosteMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCosteMantenimientoActionPerformed
       dialogCosteMantenimiento.setVisible(true);
    }//GEN-LAST:event_btnCosteMantenimientoActionPerformed
    //Se hace el calculo de total de la suma de los tres variables.
    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
       int Instalacion;
       int Formacion;
       int Mantenimiento;
       int suma;
       Instalacion=Integer.parseInt(txtCosteInstalacion.getText());
       Formacion=Integer.parseInt(txtCosteFormacion.getText());
       Mantenimiento=Integer.parseInt(txtCosteMantenimiento.getText());
       suma=Instalacion+Formacion+Mantenimiento;
       etiTotal.setText(""+suma);
    }//GEN-LAST:event_btnCalcularActionPerformed
    //Se hace el calculo del coste de instalacion.
    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        int CopiasSimpli;
        int CopiasComple;
        int instalacion;
        CopiasSimpli=Integer.parseInt(txtCopiasSimplificada.getText());
        CopiasComple=Integer.parseInt(txtCopiasCompleta.getText());
        instalacion=(120*CopiasSimpli)+(180*CopiasComple);
        txtCosteInstalacion.setText(""+instalacion);
        dialogCosteInstalacion.dispose();
    }//GEN-LAST:event_btnAceptarActionPerformed
    //Boton para salir del Cuadro de Instalacion
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dialogCosteInstalacion.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed
        //Se hace el calculo del coste de Formacion.
    private void btnAceptarFormacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarFormacionActionPerformed
       int NAlumnos;
       int NHoras;
       int total;
       NAlumnos=Integer.parseInt(txtNAlumnos.getText());
       NHoras=Integer.parseInt(txtNHoras.getText());
       total=NAlumnos*NHoras*10;
       txtCosteFormacion.setText(""+total);
       dialogCosteFormacion.dispose();
    }//GEN-LAST:event_btnAceptarFormacionActionPerformed
    //Boton para cerrar el cuadro de Formacion.
    private void btnCancelarFormacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarFormacionActionPerformed
        dialogCosteFormacion.dispose();
    }//GEN-LAST:event_btnCancelarFormacionActionPerformed
    //Se tiene las opciones de calculo de mantenimient en el Cuadro de Dialogo de Mantenimiento.
    private void btnAceptarMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarMantenimientoActionPerformed
        if(btpAnual.isSelected()){
            txtCosteMantenimiento.setText(""+600);
        }else if(btpSemestral.isSelected()){
            txtCosteMantenimiento.setText(""+350);
        }else if(btpPuesta.isSelected()){
            txtCosteMantenimiento.setText(""+200);
        }
        dialogCosteMantenimiento.dispose();
    }//GEN-LAST:event_btnAceptarMantenimientoActionPerformed
    //Boton para cerrar el cuadro de dialogo de mantenimiento.
    private void btnCancelarMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarMantenimientoActionPerformed
        dialogCosteMantenimiento.dispose();
    }//GEN-LAST:event_btnCancelarMantenimientoActionPerformed
    //Boton para activar el cuadro de informacion.
    private void btnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoActionPerformed
        dialogInfo.setVisible(true);
    }//GEN-LAST:event_btnInfoActionPerformed
    //Boton para cerrar el Cuadro de dialogo de informacion.
    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
       dialogInfo.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed
    //Centra nuestro cuadro de presentacion
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       int x=(int) (Toolkit.getDefaultToolkit().getScreenSize().getWidth()/2 -  dialogoPres.getWidth()/2);
       int y=(int) (Toolkit.getDefaultToolkit().getScreenSize().getHeight()/2 -  dialogoPres.getHeight()/2);
       dialogoPres.setLocation(x,y);
       dialogoPres.setVisible(true);
    }//GEN-LAST:event_formWindowOpened
//    Abre nuestro dialogo de presentacion.
    private void dialogoPresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dialogoPresMouseClicked
        dialogoPres.dispose();
    }//GEN-LAST:event_dialogoPresMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cuadrodedialogo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cuadrodedialogo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cuadrodedialogo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cuadrodedialogo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cuadrodedialogo1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAceptarFormacion;
    private javax.swing.JButton btnAceptarMantenimiento;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCancelarFormacion;
    private javax.swing.JButton btnCancelarMantenimiento;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnCosteFormacion;
    private javax.swing.JButton btnCosteInstalacion;
    private javax.swing.JButton btnCosteMantenimiento;
    private javax.swing.JButton btnInfo;
    private javax.swing.JRadioButton btpAnual;
    private javax.swing.JRadioButton btpPuesta;
    private javax.swing.JRadioButton btpSemestral;
    private javax.swing.JDialog dialogCosteFormacion;
    private javax.swing.JDialog dialogCosteInstalacion;
    private javax.swing.JDialog dialogCosteMantenimiento;
    private javax.swing.JDialog dialogInfo;
    private javax.swing.JDialog dialogoPres;
    private javax.swing.JLabel etiTotal;
    private javax.swing.ButtonGroup grupoMantenimento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextField txtCopiasCompleta;
    private javax.swing.JTextField txtCopiasSimplificada;
    private javax.swing.JTextField txtCosteFormacion;
    private javax.swing.JTextField txtCosteInstalacion;
    private javax.swing.JTextField txtCosteMantenimiento;
    private javax.swing.JTextField txtNAlumnos;
    private javax.swing.JTextField txtNHoras;
    // End of variables declaration//GEN-END:variables
}
