package lenguajejava;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Melvin
 */
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.*;

public class ratoncodigo extends javax.swing.JFrame {
    //Se declaran las etiquetas a utilizar.
    JLabel gris, negro;

    /**
     * Creates new form ratoncodigo
     */
    public ratoncodigo() {
        initComponents();
        crearventana();//Se manda a llamar el metodo creado
    }
    //Se crea un metodo para crear los componentes.
    public void crearventana() {
        //Se le asigna tamaño al frame
        this.setSize(250, 250);
        //Se le asigna tamaño,color, texto y posicion a la etiqueta y se agrega al Frame.
        gris = new JLabel();
        gris.setBounds(10, 10, 100, 100);
        gris.setOpaque(true);
        gris.setBackground(Color.GRAY);
        gris.setText("Etiqueta");
        gris.setHorizontalAlignment(SwingConstants.CENTER);
        this.getContentPane().add(gris);

        //Se le asigna tamaño,color y posicion a la etiqueta y se agrega al Frame.
        negro = new JLabel();
        negro.setBounds(20, 20, 100, 100);
        negro.setOpaque(true);
        negro.setBackground(Color.BLACK);
        this.getContentPane().add(negro);
        
        //Se crean los eventos de mouse para el funcionamiento.
        gris.addMouseListener(new MouseAdapter() {

            public void mouseEntered(MouseEvent evt) {
                grisMouseEntered(evt);
            }

            public void mouseExited(MouseEvent evt) {
                grisMouseExited(evt);
            }

            public void mousePressed(MouseEvent evt) {
                grisMousePressed(evt);
            }

            public void mouseReleased(MouseEvent evt) {
                grisMouseReleased(evt);
            }

        });

    }
    //Metodo para cambiar el texto miesntras el mouse este en la etiqueta.
    public void grisMouseReleased(MouseEvent evt) {
        gris.setBounds(10, 10, 100, 100);
        gris.setText("Pulsado");
    }
    //Metodo cuando el mouse este dentro se le cambiara el texto a la etiqueta
    public void grisMouseEntered(MouseEvent evt) {
        gris.setText("Pulsame");
    }

    //Metodo para regresar a su estado original
    public void grisMouseExited(MouseEvent evt) {
        gris.setText("Etiqueta");
    }

    //Si esta pulsado nos indicara que lo esta
    public void grisMousePressed(MouseEvent evt) {
        gris.setBounds(20, 20, 100, 100);
        gris.setText("Esta pulsado");
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ratoncodigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ratoncodigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ratoncodigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ratoncodigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ratoncodigo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
