
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Melvin
 */
public class progresion extends javax.swing.JFrame {

    /**
     * Creates new form progresion
     */
    public progresion() {
        initComponents();
        metodosteclado();
    }
    //Metodo para obtener los numeros.
    public void rellenar() {

        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        int i;
        int inicio = Integer.parseInt(txtInicio.getText());
        int fin = Integer.parseInt(txtFin.getText());
        int intervalo = Integer.parseInt(txtIntervalo.getText());
        if (fin > inicio) {
            for (inicio = inicio; inicio <= fin; inicio += intervalo) {
                modelo.addElement(inicio);
            }
            cboProgresion.setModel(modelo);
        } else {
            JOptionPane.showMessageDialog(null, "El tamaño de inicio debe ser menor al final");
        }
 
    }
    //Metodos para los eventos.
    public void metodosteclado() {
        btnRellenar.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnRellenarActionPerformed(evt);
            }
        });
        btnVaciar.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnVaciarActionPerformed(evt);
            }
        });
        cboProgresion.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                cboProgresionActionPerformed(evt);
            }
        });
        txtFin.addKeyListener(new KeyAdapter(){
            public void keyTyped(KeyEvent evt){
                txtFinKeyTyped(evt);
            }
        });
        txtInicio.addKeyListener(new KeyAdapter(){
            public void keyTyped(KeyEvent evt){
                txtInicioKeyTyped(evt);
            }
        });
        txtIntervalo.addKeyListener(new KeyAdapter(){
            public void keyTyped(KeyEvent evt){
                txtIntervaloKeyTyped(evt);
            }
        });
    }
    
    //Metodo de validacion de teclado
    public void verif(KeyEvent evt){
        char validar = evt.getKeyChar();
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingrese solo numeros");
        }
        }
    //Metodo para borrar.
    public void borrar() {
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        cboProgresion.setModel(modelo);
    }
    //Eventos de acciones
    public void btnRellenarActionPerformed(ActionEvent evt) {
        rellenar();
    }

    public void btnVaciarActionPerformed(ActionEvent evt) {
        borrar();
    }
    public void cboProgresionActionPerformed(ActionEvent evt) {
     etiResultado.setText(cboProgresion.getSelectedItem().toString());
    }
    //Eventos para validacion.
    public void txtFinKeyTyped(KeyEvent evt){
        verif(evt);
    }
    public void txtInicioKeyTyped(KeyEvent evt){
        verif(evt);
    }
    public void txtIntervaloKeyTyped(KeyEvent evt){
        verif(evt);
    }
    /**
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cboProgresion = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtInicio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFin = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtIntervalo = new javax.swing.JTextField();
        btnRellenar = new javax.swing.JButton();
        btnVaciar = new javax.swing.JButton();
        etiResultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Progresión");

        jLabel2.setText("Inicio: ");

        jLabel3.setText("Fin: ");

        jLabel4.setText("Intervalo");

        btnRellenar.setText("Rellenar");

        btnVaciar.setText("Vaciar");

        etiResultado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addComponent(cboProgresion, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4))
                            .addGap(10, 10, 10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtIntervalo)
                                .addComponent(txtFin)
                                .addComponent(txtInicio))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnVaciar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRellenar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(etiResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboProgresion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtIntervalo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnRellenar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVaciar)
                .addGap(18, 18, 18)
                .addComponent(etiResultado, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(progresion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(progresion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(progresion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(progresion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new progresion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRellenar;
    private javax.swing.JButton btnVaciar;
    private javax.swing.JComboBox<String> cboProgresion;
    private javax.swing.JLabel etiResultado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtFin;
    private javax.swing.JTextField txtInicio;
    private javax.swing.JTextField txtIntervalo;
    // End of variables declaration//GEN-END:variables
}
