/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lenguajejava;

/**
 *
 * @author Melvin
 */
public class ejemploseis extends javax.swing.JFrame {

    /**
     * Creates new form ejemploseis
     */
    public ejemploseis() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiNombre = new javax.swing.JLabel();
        btnEsquina = new javax.swing.JButton();
        btnAgrandar = new javax.swing.JButton();
        btnCentro = new javax.swing.JButton();
        btnAchicar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        etiNombre.setBackground(new java.awt.Color(0, 204, 204));
        etiNombre.setText("Melvin Paul Gonzalez Pascual");
        etiNombre.setOpaque(true);

        btnEsquina.setText("Esquina");
        btnEsquina.setPreferredSize(new java.awt.Dimension(80, 23));
        btnEsquina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEsquinaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEsquinaMouseExited(evt);
            }
        });
        btnEsquina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsquinaActionPerformed(evt);
            }
        });

        btnAgrandar.setText("Agrandar");
        btnAgrandar.setMinimumSize(new java.awt.Dimension(80, 23));
        btnAgrandar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgrandarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgrandarMouseExited(evt);
            }
        });
        btnAgrandar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgrandarActionPerformed(evt);
            }
        });

        btnCentro.setText("Centro");
        btnCentro.setPreferredSize(new java.awt.Dimension(80, 23));
        btnCentro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCentroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCentroMouseExited(evt);
            }
        });
        btnCentro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCentroActionPerformed(evt);
            }
        });

        btnAchicar.setText("Achicar");
        btnAchicar.setPreferredSize(new java.awt.Dimension(80, 23));
        btnAchicar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAchicarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAchicarMouseExited(evt);
            }
        });
        btnAchicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAchicarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEsquina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCentro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(btnAgrandar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAchicar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(etiNombre))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(etiNombre)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAchicar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgrandar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCentro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEsquina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(214, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Metodo que nos manda la etiqueta a la esquina.
    private void btnEsquinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsquinaActionPerformed
        etiNombre.setLocation(1, 1);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEsquinaActionPerformed
    //Metodo que nos centra la etiqueta.
    private void btnCentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCentroActionPerformed
        etiNombre.setLocation(110,145);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCentroActionPerformed
    //Metodo que nos hace mas grande la etiquta
    private void btnAgrandarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgrandarActionPerformed
        etiNombre.setSize(200,50);
    // TODO add your handling code here:
    }//GEN-LAST:event_btnAgrandarActionPerformed
    //Metodo que nos hace mas paqueña la etiquta
    private void btnAchicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAchicarActionPerformed
         etiNombre.setSize(80,20);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAchicarActionPerformed
    //Metodo que nos regresa al tamaño de nuestro boton.
    private void btnEsquinaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEsquinaMouseEntered
        btnEsquina.setSize(90, 30);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEsquinaMouseEntered
    //Metodo que nos regresa al tamaño de nuestro boton.
    private void btnCentroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCentroMouseEntered
        btnCentro.setSize(90, 30);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCentroMouseEntered
    //Metodo que nos regresa al tamaño de nuestro boton.
    private void btnAgrandarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgrandarMouseEntered
       btnAgrandar.setSize(90, 30);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgrandarMouseEntered
    //Metodo que nos regresa al tamaño de nuestro boton.
    private void btnAchicarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAchicarMouseEntered
        btnAchicar.setSize(90, 30);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAchicarMouseEntered
    //Metodo que nos hace incrementar el tamaño del boton.
    private void btnEsquinaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEsquinaMouseExited
        btnEsquina.setSize(80,23);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEsquinaMouseExited
    //Metodo que nos hace incrementar el tamaño del boton.
    private void btnCentroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCentroMouseExited
        btnCentro.setSize(80,23);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCentroMouseExited
    //Metodo que nos hace incrementar el tamaño del boton.
    private void btnAgrandarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgrandarMouseExited
        btnAgrandar.setSize(80,23);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgrandarMouseExited
    //Metodo que nos hace incrementar el tamaño del boton.
    private void btnAchicarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAchicarMouseExited
       btnAchicar.setSize(80,23);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAchicarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ejemploseis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ejemploseis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ejemploseis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ejemploseis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ejemploseis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAchicar;
    private javax.swing.JButton btnAgrandar;
    private javax.swing.JButton btnCentro;
    private javax.swing.JButton btnEsquina;
    private javax.swing.JLabel etiNombre;
    // End of variables declaration//GEN-END:variables
}
