/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lenguajejava;

import java.awt.Color;

/**
 *
 * @author Melvin
 */
public class ejemplosiete extends javax.swing.JFrame {

    /**
     * Creates new form ejemplosiete
     */
    public ejemplosiete() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAzul = new javax.swing.JButton();
        btnRojo = new javax.swing.JButton();
        btnVerde = new javax.swing.JButton();
        btnFondoAzul = new javax.swing.JButton();
        btnFondoRojo = new javax.swing.JButton();
        btnFondoVerde = new javax.swing.JButton();
        btnTransparente = new javax.swing.JButton();
        btnOpaca = new javax.swing.JButton();
        etiTexto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAzul.setText("Azul");
        btnAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAzulActionPerformed(evt);
            }
        });

        btnRojo.setText("Rojo");
        btnRojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRojoActionPerformed(evt);
            }
        });

        btnVerde.setText("Verde");
        btnVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerdeActionPerformed(evt);
            }
        });

        btnFondoAzul.setText("Fondo Azul");
        btnFondoAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFondoAzulActionPerformed(evt);
            }
        });

        btnFondoRojo.setText("Fondo Rojo");
        btnFondoRojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFondoRojoActionPerformed(evt);
            }
        });

        btnFondoVerde.setText("Fondo Verde");
        btnFondoVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFondoVerdeActionPerformed(evt);
            }
        });

        btnTransparente.setText("Transparente");
        btnTransparente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransparenteActionPerformed(evt);
            }
        });

        btnOpaca.setText("Opaca");
        btnOpaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpacaActionPerformed(evt);
            }
        });

        etiTexto.setText("Holaaaaaaaaaaaaa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(etiTexto)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnFondoAzul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAzul, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(btnFondoRojo))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRojo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnFondoVerde, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVerde, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(btnTransparente)
                .addGap(36, 36, 36)
                .addComponent(btnOpaca, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiTexto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAzul)
                    .addComponent(btnRojo)
                    .addComponent(btnVerde))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFondoAzul)
                    .addComponent(btnFondoRojo)
                    .addComponent(btnFondoVerde))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTransparente)
                    .addComponent(btnOpaca))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Metodo para cambiar el color
    private void btnAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAzulActionPerformed
        etiTexto.setForeground(Color.BLUE);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAzulActionPerformed

    private void btnRojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRojoActionPerformed
       etiTexto.setForeground(Color.RED);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRojoActionPerformed

    private void btnVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerdeActionPerformed
        etiTexto.setForeground(Color.GREEN);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerdeActionPerformed
    //Cambia el color del fondo de las etiquetas.
    private void btnFondoAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFondoAzulActionPerformed
        etiTexto.setBackground(Color.BLUE);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFondoAzulActionPerformed

    private void btnFondoRojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFondoRojoActionPerformed
        etiTexto.setBackground(Color.RED);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFondoRojoActionPerformed

    private void btnFondoVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFondoVerdeActionPerformed
        etiTexto.setBackground(Color.GREEN);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFondoVerdeActionPerformed
      //Metodo para cambiar si son opaca o no.
    private void btnTransparenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransparenteActionPerformed
        etiTexto.setOpaque(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTransparenteActionPerformed

    private void btnOpacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpacaActionPerformed
        etiTexto.setOpaque(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOpacaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ejemplosiete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ejemplosiete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ejemplosiete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ejemplosiete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ejemplosiete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAzul;
    private javax.swing.JButton btnFondoAzul;
    private javax.swing.JButton btnFondoRojo;
    private javax.swing.JButton btnFondoVerde;
    private javax.swing.JButton btnOpaca;
    private javax.swing.JButton btnRojo;
    private javax.swing.JButton btnTransparente;
    private javax.swing.JButton btnVerde;
    private javax.swing.JLabel etiTexto;
    // End of variables declaration//GEN-END:variables
}
